<<<<<<< Updated upstream
# Generated by Django 3.2.9 on 2022-01-03 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
=======
# Generated by Django 3.2.9 on 2022-01-02 09:31

from django.db import migrations, models
>>>>>>> Stashed changes


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< Updated upstream
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
=======
>>>>>>> Stashed changes
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=50, null=True)),
                ('bi', models.CharField(max_length=14, null=True)),
<<<<<<< Updated upstream
                ('telefone', models.CharField(max_length=16, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
=======
                ('telefone', models.CharField(max_length=13, null=True)),
>>>>>>> Stashed changes
            ],
        ),
    ]
