# Generated by Django 3.2.8 on 2021-11-13 05:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='descricao',
            field=models.CharField(default=django.utils.timezone.now, max_length=155, verbose_name='Descrição'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atividade',
            name='detalhes',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atividade',
            name='numero',
            field=models.IntegerField(default=django.utils.timezone.now, verbose_name='Número'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atividade',
            name='pontos',
            field=models.DecimalField(decimal_places=1, default=django.utils.timezone.now, max_digits=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campo',
            name='descricao',
            field=models.CharField(default=django.utils.timezone.now, max_length=150, verbose_name='Descrição'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campo',
            name='nome',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
