# Generated by Django 3.2.9 on 2021-12-06 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro1', '0002_campus_classe_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='numero',
            field=models.IntegerField(unique=True, verbose_name='Número'),
        ),
    ]
