<<<<<<< Updated upstream
# Generated by Django 3.2.9 on 2022-01-03 10:12
=======
# Generated by Django 3.2.9 on 2022-01-02 09:31
>>>>>>> Stashed changes

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro1', '0003_alter_atividade_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='detalhes',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
